version: '3.8'
services:
  backend:
    build: .
    container_name: confhub-backend
    restart: unless-stopped
    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST:-192.168.88.110}:5433/confhub_db
      - SPRING_DATASOURCE_USERNAME=confhub_user
      - SPRING_DATASOURCE_PASSWORD=StrongPass123
      - APP_FRONTEND_URL=${APP_FRONTEND_URL:-http://192.168.88.110:4000}
      - APP_BASE_URL=${APP_BASE_URL:-http://192.168.88.110:8080}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL:-http://192.168.88.110:8080/api/v1/payment/vnpay-callback}
