spring.application.name=confms
# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/confms_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# JWT Configuration
app.jwt.secret=YXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNkYXNk
app.jwt.expiration-ms=86400000

## SQL Init (seed data)
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sugoihito0201@gmail.com
spring.mail.password=lfzg fsxp ewdv gkkh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URLs
app.base-url=http://localhost:8080
app.frontend-url=http://localhost:3000

# File upload configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# VNPAY Configuration
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmn-code=ZMNARP7X
vnpay.secret-key=3H30ARTPZYUZ4829VVM0P4BUG4GRYMRK
vnpay.return-url=http://localhost:8080/api/v1/payment/vnpay-callback
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction