package com.capstone.confhub.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class AIChatRequest {

    @NotBlank(message = "Message is required")
    @Size(max = 4000, message = "Message must not exceed 4000 characters")
    private String message;

    /** Optional: conference context for the chat */
    private Integer conferenceId;

    /** Session ID for conversation continuity (generated by frontend) */
    @NotBlank(message = "Session ID is required")
    @Size(max = 64, message = "Session ID must not exceed 64 characters")
    private String sessionId;
}
