package com.capstone.confhub.utils.enums;

public enum PaperStatus {
    SUBMITTED,
    UNDER_REVIEW,
    AWAITING_DECISION,
    ACCEPTED,
    REJECTED,
    AWAITING_REGISTRATION,
    REGISTERED,
    AWAITING_CAMERA_READY,
    CAMERA_READY_SUBMITTED,
    CAMERA_READY_REJECTED,
    PUBLISHED,
    WITHDRAWN
}
