package com.capstone.confms.entity.enums;

public enum ActivityType {
    PAPER_SUBMISSION,
    EDIT_SUBMISSION,
    SUPPLEMENTARY_MATERIAL,
    SENIOR_META_REVIEWER_BIDDING,
    META_REVIEWER_BIDDING,
    REVIEWER_BIDDING,
    META_REVIEW_SUBMISSION,
    REVIEW_SUBMISSION,
    REVIEW_DISCUSSION,
    AUTHOR_FEEDBACK,
    AUTHOR_NOTIFICATION,
    REVISION_SUBMISSION,
    CAMERA_READY_SUBMISSION
}
